spring.application.name=luxzera 
# ==========================================
# NEON POSTGRESQL DATABASE CONNECTION
# ==========================================
spring.datasource.url=jdbc:postgresql://ep-royal-feather-aohtry79-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_CNLRDB0K6ySi
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE ARCHITECTURAL SETTINGS
# ==========================================
# Automatically updates your database tables to match your Java @Entity classes
spring.jpa.hibernate.ddl-auto=update

# Ensures Hibernate optimizes the SQL commands specifically for PostgreSQL features
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Prints every raw SQL query to the IntelliJ console for debugging
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true